package ua.vika;

/**
 * Created by zidd on 3/24/14.
 */

//TODO
public enum Subject {
    CIRCUITRY, COMPUTER_GRAPHICS,ECONOMY, ENGLISH,HIGHER_MATHEMATICS, INFORMATION_SYSTEMS, LIFE_SAFETY, NETWORKING, PHYSICS, PROBABILITY_THEORY, UKRAINIAN_LANGUAGE
}
